// Mocks generated by Mockito 5.4.6 from annotations
// in build_buster/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:build_buster/model/data/dev_project.dart' as _i6;
import 'package:build_buster/model/data/docker_system_df.dart' as _i9;
import 'package:build_buster/model/data/gradle_cache.dart' as _i3;
import 'package:build_buster/model/data/maven_local.dart' as _i2;
import 'package:build_buster/model/data/npm_cache.dart' as _i5;
import 'package:build_buster/model/data/pub_cache.dart' as _i4;
import 'package:build_buster/model/sources/helper_source.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMavenLocal_0 extends _i1.SmartFake implements _i2.MavenLocal {
  _FakeMavenLocal_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGradleCache_1 extends _i1.SmartFake implements _i3.GradleCache {
  _FakeGradleCache_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePubCache_2 extends _i1.SmartFake implements _i4.PubCache {
  _FakePubCache_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNpmCache_3 extends _i1.SmartFake implements _i5.NpmCache {
  _FakeNpmCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDevProjectCollection_4 extends _i1.SmartFake
    implements _i6.DevProjectCollection {
  _FakeDevProjectCollection_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HelperSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHelperSource extends _i1.Mock implements _i7.HelperSource {
  MockHelperSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i9.DockerSystemDf>> fetchDockerSystemDf() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDockerSystemDf, []),
            returnValue: _i8.Future<List<_i9.DockerSystemDf>>.value(
              <_i9.DockerSystemDf>[],
            ),
          )
          as _i8.Future<List<_i9.DockerSystemDf>>);

  @override
  _i8.Future<bool> deleteDockerCache() =>
      (super.noSuchMethod(
            Invocation.method(#deleteDockerCache, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i2.MavenLocal> fetchMavenLocal() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMavenLocal, []),
            returnValue: _i8.Future<_i2.MavenLocal>.value(
              _FakeMavenLocal_0(this, Invocation.method(#fetchMavenLocal, [])),
            ),
          )
          as _i8.Future<_i2.MavenLocal>);

  @override
  _i8.Future<bool> deleteMavenLocal() =>
      (super.noSuchMethod(
            Invocation.method(#deleteMavenLocal, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.GradleCache> fetchGradleCache() =>
      (super.noSuchMethod(
            Invocation.method(#fetchGradleCache, []),
            returnValue: _i8.Future<_i3.GradleCache>.value(
              _FakeGradleCache_1(
                this,
                Invocation.method(#fetchGradleCache, []),
              ),
            ),
          )
          as _i8.Future<_i3.GradleCache>);

  @override
  _i8.Future<bool> deleteGradleCache() =>
      (super.noSuchMethod(
            Invocation.method(#deleteGradleCache, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i4.PubCache> fetchPubCache() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPubCache, []),
            returnValue: _i8.Future<_i4.PubCache>.value(
              _FakePubCache_2(this, Invocation.method(#fetchPubCache, [])),
            ),
          )
          as _i8.Future<_i4.PubCache>);

  @override
  _i8.Future<bool> deletePubCache() =>
      (super.noSuchMethod(
            Invocation.method(#deletePubCache, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.NpmCache> fetchNpmCache() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNpmCache, []),
            returnValue: _i8.Future<_i5.NpmCache>.value(
              _FakeNpmCache_3(this, Invocation.method(#fetchNpmCache, [])),
            ),
          )
          as _i8.Future<_i5.NpmCache>);

  @override
  _i8.Future<bool> deleteNpmCache() =>
      (super.noSuchMethod(
            Invocation.method(#deleteNpmCache, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.DevProjectCollection> fetchProjects(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProjects, [path]),
            returnValue: _i8.Future<_i6.DevProjectCollection>.value(
              _FakeDevProjectCollection_4(
                this,
                Invocation.method(#fetchProjects, [path]),
              ),
            ),
          )
          as _i8.Future<_i6.DevProjectCollection>);

  @override
  _i8.Future<bool> deleteBuildArtifacts(String? projectPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuildArtifacts, [projectPath]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> deleteAllBuildArtifacts(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBuildArtifacts, [path]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> onShutdown() =>
      (super.noSuchMethod(
            Invocation.method(#onShutdown, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> health() =>
      (super.noSuchMethod(
            Invocation.method(#health, []),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(this, Invocation.method(#health, [])),
            ),
          )
          as _i8.Future<String>);
}
